#!/usr/bin/env bash

#: exec_target = cli

## Import/export environment specific configuration for a site
##
## Usage: fin kit/conf <args>

#-------------------------- BEGIN: Execution --------------------------------
cd ${PROJECT_ROOT}/${DOCROOT}
drush kit:conf "$@"
#-------------------------- CLOSE: Execution --------------------------------
