#!/usr/bin/env bash

#: exec_target = cli

## Run gulp in the theme source directory
##
## Usage: fin kit/gulp <args>

#-------------------------- BEGIN: Execution --------------------------------
cd ${PROJECT_ROOT}/source
npm run gulp "$@"
#-------------------------- CLOSE: Execution --------------------------------
