#!/usr/bin/env bash

#: exec_target = cli

## Lint and test the projects' custom and source files.
##
## Usage: fin kit/lint

set -e
SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#-------------------------- BEGIN: Execution --------------------------------
"${SCRIPT_PATH}/gulp" test
"${SCRIPT_PATH}/phpcs" ${PROJECT_ROOT}/${DOCROOT}/modules/custom/
"${SCRIPT_PATH}/phpcs" ${PROJECT_ROOT}/${DOCROOT}/themes/custom/
#-------------------------- CLOSE: Execution --------------------------------
